#[Info]
site_name: Devhiker'Website
site_url: https://cxyhuky.github.io/
site_author: devhiker

copyright: Copyright &copy; 2025 devhiker
#[Config]
#[Repo Config]
repo_url: https://github.com/devhiker/cxyhuky.github.io 
repo_name: devhiker.github.io

#[扩展]
extra:
    consent:
        title: Cookie consent
        description: >-
          We use cookies to recognize your repeated visits and preferences, as well
          as to measure the effectiveness of our documentation and whether users
          find what they're searching for. With your consent, you're helping us to
          make our documentation better.
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/devhiker

        - icon: fontawesome/solid/paper-plane
          link: mailto:devhiker.xyz@gmail.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - admonition    
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

#[UI]
theme:
    name: 'material'                            #主题名
    favicon: assets/logo/cxyhuky-icon.png
    language: zh
    palette:
        primary: indigo
    custom_dir: docs/templates
    icon:
        logo: material/state-machine
        repo: fontawesome/brands/github         #指定仓库图标
    features:
        - navigation.tabs                       #在header中添加导航条
        - navigation.tabs.sticky
        - navigation.top                        #回到顶部 
        - navigation.path
        - navigation.instant
        - navigation.indexes
        - navigation.prune
        - navigation.sections
        - search.suggest
        - content.code.annotate

plugins:
  - autorefs
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - blog:
        draft: true
  - search:
#   - minify:
#       minify_html: true
#   - bibtex:
#       bib_file: "docs/references.bib"
#       csl_file: "docs/ieee.csl"
#       cite_inline: false

extra_css:
  - css/extra.css  # 加载自定义 CSS

nav:
- Blog:
    - blog/index.md
